In [3]:
import numpy as np
import pandas as pd

In [4]:
r_cols = ['_id','dish_id_num','dish_name','restaurant_id','average_rating','features',
          'description','tags','rating_ids', 'obj_id']

dish_dirty = pd.read_csv('dish_dirty.csv', sep=',', names=r_cols, encoding='latin-1')

In [5]:
dish_dirty = dish_dirty.drop(0)

In [6]:
dish_dirty

,_id,dish_id_num,dish_name,restaurant_id,average_rating,features,description,tags,rating_ids,obj_id
1,ObjectId(603ab53b88dbe9c89607dfa8),1,Pad Thai,1,5,NaN,"Thin rice noodles stir-fried with egg, green o...",NaN,NaN,603ab53b88dbe9c89607dfa8
2,ObjectId(603ab53b88dbe9c89607dfab),2,Pad Kee Mao,1,1.3,NaN,"Wide rice noodles stir-fried with egg, fresh c...",NaN,NaN,603ab53b88dbe9c89607dfab
3,ObjectId(603ab53b88dbe9c89607dfaa),3,Green Curry,1,4,NaN,"Thai Green curry paste with coconut milk, basi...",NaN,NaN,603ab53b88dbe9c89607dfaa
4,ObjectId(603ab53b88dbe9c89607dfa7),4,Panang Curry,1,2.5,NaN,"Thai Panang curry paste with coconut milk, kaf...",NaN,NaN,603ab53b88dbe9c89607dfa7
5,ObjectId(603ab53b88dbe9c89607dfa9),5,Pad Ka Pao,1,1.5,NaN,"Fresh ground chilis, stir-fried with basil lea...",NaN,NaN,603ab53b88dbe9c89607dfa9
6,ObjectId(603ab53b88dbe9c89607dfac),6,Pra Ram,1,5,NaN,"Your choice of meat with steamed vegetables, t...",NaN,NaN,603ab53b88dbe9c89607dfac
7,ObjectId(603ab53b88dbe9c89607dfad),7,Pad See Ew,1,2.1,NaN,"Wide rice noodles stir-fried with egg, sweet s...",NaN,NaN,603ab53b88dbe9c89607dfad
8,ObjectId(603ab53b88dbe9c89607dfae),8,Crispy Chicken Fried Rice,1,3.3,NaN,"Fried rice with egg, onions, carrots, green pe...",NaN,NaN,603ab53b88dbe9c89607dfae
9,ObjectId(603ab53b88dbe9c89607dfaf),9,Kao Pad Ka Pao,1,5,NaN,"Spicy fried rice with egg, fresh ground chili,...",NaN,NaN,603ab53b88dbe9c89607dfaf
10,ObjectId(603ab53b88dbe9c89607dfb0),10,Sweet Sticky Rice with Mango,1,2.3,NaN,NaN,NaN,NaN,603ab53b88dbe9c89607dfb0
11,ObjectId(603ab53b88dbe9c89607dfb2),11,Grilled Lobster Club,2,4.1,NaN,"bacon, lettuce, tomato, Dijon aioli",NaN,NaN,603ab53b88dbe9c89607dfb2
12,ObjectId(603ab53b88dbe9c89607dfb1),12,Turkey Wrap,2,5,NaN,"VT turkey, cheddar, cranberry, mayo",NaN,NaN,603ab53b88dbe9c89607dfb1
13,ObjectId(603ab53b88dbe9c89607dfb3),13,Fried Buttermilk Chicken Sandwhich,2,1.2,NaN,"Spicy mayo, slaw, pickles",NaN,NaN,603ab53b88dbe9c89607dfb3
14,ObjectId(603ab53b88dbe9c89607dfb4),14,"The ""Murph"" Burger",2,1.8,NaN,"American cheese, crispy shallots, bacon, Baja ...",NaN,NaN,603ab53b88dbe9c89607dfb4
15,ObjectId(603ab53b88dbe9c89607dfb5),15,Grilled Beef Ribeye,2,1.2,NaN,"Mashed potato, red wine demi glaze",NaN,NaN,603ab53b88dbe9c89607dfb5
16,ObjectId(603ab53b88dbe9c89607dfb6),16,Irish Shepards Pie,2,1.1,NaN,"Ground lamb, peas, onions, corn, carrots, mash...",NaN,NaN,603ab53b88dbe9c89607dfb6
17,ObjectId(603ab53b88dbe9c89607dfb7),17,Smoked Barbeque Pulled Pork Taco,2,1.5,NaN,"Corn Slaw, pickled onion, feta, radish, Pico, ...",NaN,NaN,603ab53b88dbe9c89607dfb7
18,ObjectId(603ab53b88dbe9c89607dfb9),18,Grilled Salmon,2,4.6,NaN,"Winter Slaw, horseradish sauce",NaN,NaN,603ab53b88dbe9c89607dfb9
19,ObjectId(603ab53b88dbe9c89607dfba),19,Seared Pork Chop,2,4.1,NaN,"Pan seared pork chop, potato confit, green bea...",NaN,NaN,603ab53b88dbe9c89607dfba
20,ObjectId(603ab53b88dbe9c89607dfb8),20,Housemade Black Bean Burger,2,4.7,NaN,"Lettuce, tomato, pickle, chipotle aioli",NaN,NaN,603ab53b88dbe9c89607dfb8
21,ObjectId(603ab53b88dbe9c89607dfbb),21,Grilled Murphy's Meatloaf,2,4.2,NaN,"Mashed potato, green beans, red wine demi",NaN,NaN,603ab53b88dbe9c89607dfbb
22,ObjectId(603ab53b88dbe9c89607dfbc),22,Certified Angus Sirloin Burger,2,4.5,NaN,"Lettuce, tomato, pickle",NaN,NaN,603ab53b88dbe9c89607dfbc
23,ObjectId(603ab53b88dbe9c89607dfbd),23,Beat Kimchi Fried Egg Sandwich,2,3.7,NaN,"Cheddar, avocado, grilled sourdough",NaN,NaN,603ab53b88dbe9c89607dfbd
24,ObjectId(603ab53b88dbe9c89607dfbe),24,Baked Fish Tacos,2,1.5,NaN,"Corn Slaw, pickled onion, feta, radish, Pico, ...",NaN,NaN,603ab53b88dbe9c89607dfbe
25,ObjectId(603ab53b88dbe9c89607dfbf),25,B.L.A.T. Wrap,2,3.7,NaN,"Bacon, lettuce, tomato, avocado, mayo",NaN,NaN,603ab53b88dbe9c89607dfbf
26,ObjectId(603ab53b88dbe9c89607dfc0),26,Vegan Risotto,2,2.9,NaN,"Butternut squash, nutritional yeast, garbanzo ...",NaN,NaN,603ab53b88dbe9c89607dfc0
27,ObjectId(603ab53b88dbe9c89607dfc1),27,Murphy's Mac'n Cheese,2,1.8,NaN,"Penne, cheddar, bread crumbs",NaN,NaN,603ab53b88dbe9c89607dfc1
28,ObjectId(603ab53b88dbe9c89607dfc2),28,Fish & Chips,2,4.9,NaN,"Fried white fish, slaw, tartar",NaN,NaN,603ab53b88dbe9c89607dfc2
29,ObjectId(603ab53b88dbe9c89607dfc4),29,Pan Seared Statler Chicken,2,1.1,NaN,"Sweet potato gratin, green beans, pan jus",NaN,NaN,603ab53b88dbe9c89607dfc4
30,ObjectId(603ab53b88dbe9c89607dfc3),30,Thai Chicken,3,1.6,NaN,"sautÃ©ed chicken strips with coconut milk, gre...",NaN,NaN,603ab53b88dbe9c89607dfc3
31,ObjectId(603ab53b88dbe9c89607dfc5),31,Fish Tacos,3,1.3,NaN,"your choice of seafood with shredded cabbage, ...",NaN,NaN,603ab53b88dbe9c89607dfc5
32,ObjectId(603ab53b88dbe9c89607dfc6),32,Pepperoni Pizza,3,2,NaN,the Classic with pepperoni,NaN,NaN,603ab53b88dbe9c89607dfc6
33,ObjectId(603ab53b88dbe9c89607dfc7),33,The Margherita,3,3.1,NaN,"ripe tomato, roasted garlic, fontina, fresh mo...",NaN,NaN,603ab53b88dbe9c89607dfc7
34,ObjectId(603ab53b88dbe9c89607dfc8),34,Half-Pound Beef Burger,3,2.8,NaN,"add cheddar, Swiss, or American, add bacon",NaN,NaN,603ab53b88dbe9c89607dfc8
35,ObjectId(603ab53b88dbe9c89607dfc9),35,Beyond Burger,3,4.5,NaN,"plant-based patty, BBQ, cheddar, avocado, cris...",NaN,NaN,603ab53b88dbe9c89607dfc9
36,ObjectId(603ab53b88dbe9c89607dfca),36,Black Bean Burger,3,1.2,NaN,"corn, peppers,onion, cheddar, Mexican spices, ...",NaN,NaN,603ab53b88dbe9c89607dfca
37,ObjectId(603ab53b88dbe9c89607dfcc),37,Turkey BLT,3,4.5,NaN,with maple aioli on grilled brioche,NaN,NaN,603ab53b88dbe9c89607dfcc
38,ObjectId(603ab53b88dbe9c89607dfcb),38,Chicken Alfredo,3,3.1,NaN,"sautÃ©ed chicken strips with bacon, garlic, ba...",NaN,NaN,603ab53b88dbe9c89607dfcb
39,ObjectId(603ab53b88dbe9c89607dfcd),39,Almond Salmon,3,4.5,NaN,"baby arugula, toasted almonds, lemon basil qui...",NaN,NaN,603ab53b88dbe9c89607dfcd
40,ObjectId(603ab53b88dbe9c89607dfce),40,Steak Tacos,3,2.2,NaN,"sliced medium rare tenderloin, lettuce, tomato...",NaN,NaN,603ab53b88dbe9c89607dfce
41,ObjectId(603ab53b88dbe9c89607dfcf),41,Fish & Chips,3,3.9,NaN,beer battered north Atlantic cod served with f...,NaN,NaN,603ab53b88dbe9c89607dfcf
42,ObjectId(603ab53b88dbe9c89607dfd0),42,Steak Tips,3,3.4,NaN,"beef tenderloin tips, grilled peppers, crispy ...",NaN,NaN,603ab53b88dbe9c89607dfd0
43,ObjectId(603ab53b88dbe9c89607dfd4),43,Four Cheese Baked Ziti,4,2.1,NaN,"Add chicken, sweet Italian sausage or meatball...",NaN,NaN,603ab53b88dbe9c89607dfd4
44,ObjectId(603ab53b88dbe9c89607dfd1),44,Chicken or Eggplant Parmesan,4,1,NaN,NaN,NaN,NaN,603ab53b88dbe9c89607dfd1
45,ObjectId(603ab53b88dbe9c89607dfd8),45,Buffalo Brick,4,4.8,NaN,"Tomato sauce, spicy chicken, tomatoes, peppers...",NaN,NaN,603ab53b88dbe9c89607dfd8
46,ObjectId(603ab53b88dbe9c89607dfd7),46,The Original Brick,4,3.3,NaN,"Mozzarella topped with tomato sauce, fresh bas...",NaN,NaN,603ab53b88dbe9c89607dfd7
47,ObjectId(603ab53b88dbe9c89607dfd2),47,Philly Cheese Steak Brick,4,3.5,NaN,"Tomato sauce, mozzarella and american cheeses,...",NaN,NaN,603ab53b88dbe9c89607dfd2
48,ObjectId(603ab53b88dbe9c89607dfd3),48,Caprese Salad,4,5,NaN,"Seasoned fresh mozzarella, fresh basil and tom...",NaN,NaN,603ab53b88dbe9c89607dfd3
49,ObjectId(603ab53b88dbe9c89607dfd5),49,Greek Salad,4,1.1,NaN,Crisp greens with classic Mediterranean veggie...,NaN,NaN,603ab53b88dbe9c89607dfd5
50,ObjectId(603ab53b88dbe9c89607dfd6),50,Prosciutto Penne Pasta with Chicken,4,4.2,NaN,Prosciutto and chicken breast tossed in a crea...,NaN,NaN,603ab53b88dbe9c89607dfd6

In [7]:
r_cols = ['tag_id', 'dish_id', 'breakfast', 'lunch', 'dinner', 'dessert', 'vegetarian',
          'vegan', 'nuts', 'thai', 'indian', 'mexican' ,'pizza', 'chinese', 'american']
dish_features = pd.read_csv('dish_features.csv', sep=',', names=r_cols, encoding='latin-1')

In [8]:
dish_features = dish_features.drop(0)

In [9]:
hello = {
    'breakfast':0, 
    'lunch':1, 
    'dinner':2,
    'dessert':3, 
    'vegetarian':4,
    'vegan':5,
    'nuts':6,
    'thai':7,
    'indian':8,
    'mexican':9,
    'pizza':10,
    'chinese':11,
    'american':12
}

In [10]:
 dish_features['dish_id'] = pd.to_numeric(dish_features['dish_id'])

In [11]:
dish_features

,tag_id,dish_id,breakfast,lunch,dinner,dessert,vegetarian,vegan,nuts,thai,indian,mexican,pizza,chinese,american
1,1,1,0,1,1,0,1,0,1,1,0,0,0,0,0
2,2,2,0,1,1,0,1,0,0,1,0,0,0,0,0
3,3,3,0,1,1,0,1,0,0,1,0,0,0,0,0
4,4,4,0,1,1,0,1,0,0,1,0,0,0,0,0
5,5,5,0,1,1,0,1,0,0,1,0,0,0,0,0
6,6,6,0,1,1,0,0,0,1,1,0,0,0,0,0
7,7,7,0,1,1,0,0,0,0,1,0,0,0,0,0
8,8,8,0,1,1,0,0,0,0,1,0,0,0,0,0
9,9,9,0,1,1,0,1,0,0,1,0,0,0,0,0
10,10,10,0,0,0,1,1,1,0,1,0,0,0,0,0
11,11,11,0,1,0,0,0,0,0,0,0,0,0,0,1
12,12,12,0,1,0,0,0,0,0,0,0,0,0,0,1
13,13,13,0,0,1,0,0,0,0,0,0,0,0,0,1
14,14,14,0,0,1,0,0,0,0,0,0,0,0,0,1
15,15,15,0,0,1,0,0,0,0,0,0,0,0,0,1
16,16,16,0,0,1,0,0,0,0,0,0,0,0,0,0
17,17,17,0,0,1,0,0,0,0,0,0,1,0,0,1
18,18,18,0,0,1,0,0,0,0,0,0,0,0,0,1
19,19,19,0,0,1,0,0,0,0,0,0,0,0,0,1
20,20,20,0,0,1,0,1,0,0,0,0,0,0,0,1
21,21,21,0,0,1,0,0,0,0,0,0,0,0,0,1
22,22,22,0,0,1,0,0,0,0,0,0,0,0,0,1
23,23,23,0,0,1,0,1,0,0,0,0,0,0,0,1
24,24,24,0,0,1,0,0,0,0,0,0,1,0,0,1
25,25,25,0,0,1,0,0,0,0,0,0,0,0,0,1
26,26,26,0,0,1,0,0,1,0,0,0,0,0,0,1
27,27,27,0,0,1,0,0,0,0,0,0,0,0,0,1
28,28,28,0,0,1,0,0,0,0,0,0,0,0,0,1
29,29,29,0,0,1,0,0,0,0,0,0,0,0,0,1
30,30,30,0,0,1,0,0,0,0,1,0,0,0,0,1
31,31,31,0,0,1,0,0,0,0,0,0,1,0,0,1
32,32,32,0,1,1,0,0,0,0,0,0,0,1,0,0
33,33,33,0,1,1,0,1,0,0,0,0,0,1,0,0
34,34,34,0,1,1,0,0,0,0,0,0,0,0,0,1
35,35,35,0,1,1,0,1,0,0,0,0,0,0,0,1
36,36,36,0,1,1,0,1,0,0,0,0,0,0,0,1
37,37,37,0,1,1,0,0,0,0,0,0,0,0,0,1
38,38,38,0,0,1,0,0,0,0,0,0,0,0,0,1
39,39,39,0,0,1,0,0,0,0,0,0,0,0,0,1
40,40,40,0,0,1,0,0,0,0,0,0,1,0,0,1
41,41,41,0,1,1,0,0,0,0,0,0,0,0,0,1
42,42,42,0,0,1,0,0,0,0,0,0,0,0,0,0
43,43,43,0,0,1,0,0,0,0,0,0,0,0,0,0
44,44,44,0,0,1,0,0,0,0,0,0,0,0,0,0
45,45,45,0,1,1,0,0,0,0,0,0,0,1,0,0
46,46,46,0,1,1,0,0,0,0,0,0,0,1,0,0
47,47,47,0,1,1,0,0,0,0,0,0,0,1,0,0
48,48,48,0,1,1,0,1,0,0,0,0,0,0,0,0
49,49,49,0,1,1,0,0,0,0,0,0,0,0,0,0
50,50,50,0,0,1,0,0,0,0,0,0,0,0,0,0

In [12]:
dish_features.loc[dish_features['dish_id'] == 2]

,tag_id,dish_id,breakfast,lunch,dinner,dessert,vegetarian,vegan,nuts,thai,indian,mexican,pizza,chinese,american
2,2,2,0,1,1,0,1,0,0,1,0,0,0,0,0

In [20]:
for row in dish_dirty.index:
    dish_dirty['features'][row] = []
#     print(dish_dirty['dish_id_num'][row])
    
    list = []
    ret_string = "db.dishes.update({\"dish_id_num\" :" + dish_dirty['dish_id_num'][row] + "}, {$set: { \"features\" : ["
    feature_row = dish_features.loc[dish_features['dish_id'] == int(dish_dirty['dish_id_num'][row])]
#     print(feature_row)
    for column in feature_row:
        if(column != 'tag_id' and column != 'dish_id'):
            
            if(int(feature_row[column].values[0]) == 1):
                ret_string = ret_string + str(hello[column]) + ","
            
    ret_string = ret_string[:-1]
    ret_string = ret_string + "]}})"
    print(ret_string)

db.dishes.update({"dish_id_num" :1}, {$set: { "features" : [1,2,4,6,7]}})
db.dishes.update({"dish_id_num" :2}, {$set: { "features" : [1,2,4,7]}})
db.dishes.update({"dish_id_num" :3}, {$set: { "features" : [1,2,4,7]}})
db.dishes.update({"dish_id_num" :4}, {$set: { "features" : [1,2,4,7]}})
db.dishes.update({"dish_id_num" :5}, {$set: { "features" : [1,2,4,7]}})
db.dishes.update({"dish_id_num" :6}, {$set: { "features" : [1,2,6,7]}})
db.dishes.update({"dish_id_num" :7}, {$set: { "features" : [1,2,7]}})
db.dishes.update({"dish_id_num" :8}, {$set: { "features" : [1,2,7]}})
db.dishes.update({"dish_id_num" :9}, {$set: { "features" : [1,2,4,7]}})
db.dishes.update({"dish_id_num" :10}, {$set: { "features" : [3,4,5,7]}})
db.dishes.update({"dish_id_num" :11}, {$set: { "features" : [1,12]}})
db.dishes.update({"dish_id_num" :12}, {$set: { "features" : [1,12]}})
db.dishes.update({"dish_id_num" :13}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :14}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :15}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :16}, {$set: { "features" : [2]}})
db.dishes.update({"dish_id_num" :17}, {$set: { "features" : [2,9,12]}})
db.dishes.update({"dish_id_num" :18}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :19}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :20}, {$set: { "features" : [2,4,12]}})
db.dishes.update({"dish_id_num" :21}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :22}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :23}, {$set: { "features" : [2,4,12]}})
db.dishes.update({"dish_id_num" :24}, {$set: { "features" : [2,9,12]}})
db.dishes.update({"dish_id_num" :25}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :26}, {$set: { "features" : [2,5,12]}})
db.dishes.update({"dish_id_num" :27}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :28}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :29}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :30}, {$set: { "features" : [2,7,12]}})
db.dishes.update({"dish_id_num" :31}, {$set: { "features" : [2,9,12]}})
db.dishes.update({"dish_id_num" :32}, {$set: { "features" : [1,2,10]}})
db.dishes.update({"dish_id_num" :33}, {$set: { "features" : [1,2,4,10]}})
db.dishes.update({"dish_id_num" :34}, {$set: { "features" : [1,2,12]}})
db.dishes.update({"dish_id_num" :35}, {$set: { "features" : [1,2,4,12]}})
db.dishes.update({"dish_id_num" :36}, {$set: { "features" : [1,2,4,12]}})
db.dishes.update({"dish_id_num" :37}, {$set: { "features" : [1,2,12]}})
db.dishes.update({"dish_id_num" :38}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :39}, {$set: { "features" : [2,12]}})
db.dishes.update({"dish_id_num" :40}, {$set: { "features" : [2,9,12]}})
db.dishes.update({"dish_id_num" :41}, {$set: { "features" : [1,2,12]}})
db.dishes.update({"dish_id_num" :42}, {$set: { "features" : [2]}})
db.dishes.update({"dish_id_num" :43}, {$set: { "features" : [2]}})
db.dishes.update({"dish_id_num" :44}, {$set: { "features" : [2]}})
db.dishes.update({"dish_id_num" :45}, {$set: { "features" : [1,2,10]}})
db.dishes.update({"dish_id_num" :46}, {$set: { "features" : [1,2,10]}})
db.dishes.update({"dish_id_num" :47}, {$set: { "features" : [1,2,10]}})
db.dishes.update({"dish_id_num" :48}, {$set: { "features" : [1,2,4]}})
db.dishes.update({"dish_id_num" :49}, {$set: { "features" : [1,2]}})
db.dishes.update({"dish_id_num" :50}, {$set: { "features" : [2]}})

In [113]:
dish_dirty.to_csv('dishes_with_features.csv')